version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: bt_auto_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bt_auto
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      
    ports:
    #<External-Port> : <InDocker-Port>
      - "3307:3306"
    volumes:
    #Keep-SQL-Data-In-This-Path
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: bt_auto
    command: npx nodemon -L server.js
    ports:
    #server port
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysql

volumes:
  mysql_data: